<a href="https://colab.research.google.com/github/Eurus-Holmes/PyTorch-Tutorials/blob/master/Getting_Started.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[4.1906e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.8101, 0.9833, 0.2505],
        [0.3211, 0.2849, 0.6044],
        [0.8746, 0.3635, 0.6035],
        [0.6569, 0.1684, 0.4116],
        [0.0088, 0.0886, 0.6449]])


Construct a matrix filled zeros and of dtype long:

In [4]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [5]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [8]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-1.3197,  0.5449,  0.7239],
        [ 0.3079,  1.0471, -0.2620],
        [ 0.0801,  0.3639,  1.3921],
        [-0.9751,  0.2855, -2.0033],
        [ 0.9147, -0.4666,  0.8210]])


Get its size:

In [11]:
print(x.size())

torch.Size([5, 3])




### Note:

`torch.Size` is in fact a tuple, so it supports all tuple operations.



# Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1

In [12]:
print(x)

tensor([[-1.3197,  0.5449,  0.7239],
        [ 0.3079,  1.0471, -0.2620],
        [ 0.0801,  0.3639,  1.3921],
        [-0.9751,  0.2855, -2.0033],
        [ 0.9147, -0.4666,  0.8210]])


In [13]:
y = torch.rand(5,3)
print(y)

tensor([[0.6984, 0.6144, 0.1857],
        [0.6608, 0.0433, 0.8483],
        [0.6670, 0.2028, 0.5131],
        [0.1229, 0.4102, 0.4315],
        [0.8529, 0.5702, 0.7609]])


In [14]:
print(x+y)

tensor([[-0.6213,  1.1594,  0.9095],
        [ 0.9688,  1.0903,  0.5862],
        [ 0.7472,  0.5667,  1.9053],
        [-0.8522,  0.6957, -1.5719],
        [ 1.7676,  0.1036,  1.5819]])


Addition: syntax 2

In [15]:
print(torch.add(x,y))

tensor([[-0.6213,  1.1594,  0.9095],
        [ 0.9688,  1.0903,  0.5862],
        [ 0.7472,  0.5667,  1.9053],
        [-0.8522,  0.6957, -1.5719],
        [ 1.7676,  0.1036,  1.5819]])


Addition: providing an output tensor as argument

In [16]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-0.6213,  1.1594,  0.9095],
        [ 0.9688,  1.0903,  0.5862],
        [ 0.7472,  0.5667,  1.9053],
        [-0.8522,  0.6957, -1.5719],
        [ 1.7676,  0.1036,  1.5819]])


Addition: in-place

In [17]:
y.add_(x)
print(y)

tensor([[-0.6213,  1.1594,  0.9095],
        [ 0.9688,  1.0903,  0.5862],
        [ 0.7472,  0.5667,  1.9053],
        [-0.8522,  0.6957, -1.5719],
        [ 1.7676,  0.1036,  1.5819]])


### NOTE

Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard NumPy-like indexing with all bells and whistles!

In [18]:
print(x[:,1])

tensor([ 0.5449,  1.0471,  0.3639,  0.2855, -0.4666])


Resizing: If you want to resize/reshape tensor, you can use `torch.view`:

In [19]:
x = torch.randn(4,4)
print(x)

tensor([[-0.9692,  0.2813, -1.0509,  1.6942],
        [ 0.6585,  0.4355,  0.2424, -0.1366],
        [ 2.3252, -0.2056,  0.0614, -0.2123],
        [-0.1051, -0.5254,  1.6995,  2.6456]])


In [21]:
y = x.view(16)
print(y)

tensor([-0.9692,  0.2813, -1.0509,  1.6942,  0.6585,  0.4355,  0.2424, -0.1366,
         2.3252, -0.2056,  0.0614, -0.2123, -0.1051, -0.5254,  1.6995,  2.6456])


In [22]:
z = x.view(-1,8)
print(z)

tensor([[-0.9692,  0.2813, -1.0509,  1.6942,  0.6585,  0.4355,  0.2424, -0.1366],
        [ 2.3252, -0.2056,  0.0614, -0.2123, -0.1051, -0.5254,  1.6995,  2.6456]])


In [23]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number

In [24]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.5547])
1.5547308921813965


## Read later:

100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described [here](https://pytorch.org/docs/stable/torch.html).

# NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array

In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [27]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [28]:
print(a)

tensor([1., 1., 1., 1., 1.])


See how the numpy array changed in value.

In [29]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [30]:
print(b)

[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [31]:
import numpy as np
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [32]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [33]:
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [34]:
print(a)

[2. 2. 2. 2. 2.]


In [35]:
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

# CUDA Tensors

Tensors can be moved onto any device using the `.to` method.

In [36]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x+y
  print(z)
  print(z.to("cpu",torch.double))

tensor([2.5547], device='cuda:0')
tensor([2.5547], dtype=torch.float64)
